apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-delete-task-api-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: todo-delete-task-api-kds14.shop
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: todo-delete-task-api
                port:
                  number: 80
