name: Terraform AKS Deploy

on: 
  workflow_dispatch

permissions:
  id-token: write      # 👈 MOST IMPORTANT
  contents: read

jobs:
  terrform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environment/dev
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Fmt
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve




