name: Terraform AKS Deploy

on: 
  workflow_dispatch

permissions:
  id-token: write      # 👈 MOST IMPORTANT
  contents: read

jobs:
  terrform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environment/dev
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: e1438469-06c5-448d-88c2-29ab744032c2
          tenant-id: 3d084a01-eb62-47fe-bb1e-748c68591432
          subscription-id: cfc0d37c-0341-4d06-bcf3-35b93770a2ee

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Fmt
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Destroy
        run: terraform destroy -auto-approve




